---

- name: Add GitHub OAuth token
  composer:
    command: config
    arguments: "-g github-oauth.github.com {{ github_oauth_token }}"
    working_dir: "/home/{{ ansible_ssh_user }}"
  changed_when: false
  when: github_oauth_token is defined

- name: Add Magento Repo OAuth token
  composer:
    command: config
    arguments: "-g http-basic.repo.magento.com {{ magento_repo_username }} {{ magento_repo_password }}"
    working_dir: "/home/{{ ansible_ssh_user }}"
  changed_when: false
  when: magento_repo_username is defined and magento_repo_password is defined
