---

- name: Check if PHP is installed
  shell: which phps
  register: php_check
  ignore_errors: yes
  changed_when: false

- name: Exit role if PHP is not installed
  meta: end_play
  when: php_check.rc == 1

- name: Check if Composer is installed
  stat:
    path: /usr/local/bin/composer
  register: composer_bin
  tags:
    - composer

- include: install.yml
  when: not composer_bin.stat.exists
  tags:
    - composer

- name: Update Composer
  become: yes
  composer:
    command: self-update
    global_command: yes
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_use_latest
  tags:
    - composer

- include: configure-oath.yml
  tags:
    - composer
    - composer_oauth
